//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerId { get; set; }
        public string cname { get; set; }
        public Nullable<int> productid { get; set; }
        public string sname { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> bill { get; set; }
    
        public virtual product product { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
